TEXT:
    SAMPLE:
        SAMPLE_SIZE: {'corpus': 0,'date': 0,'number': 0,'sub_address': 0,'id': 0,'eng_char': 0, 'task': 0, 'sequence': 5}  # 各种类型样本数量
        WORD_LENGTH: [2, 12]   # 字符长度
        WORD_LONG: 0.85  # 一定的概率字符长度不随机而取WORD_LENGTH中的最大长度
        INSERT_BLANK_PROB: 0.8    # 当字符长度少于最大长度时用空格补全为最大长度（空格只出现在两字中间）
        CHAR_SET: 'data/chars/eng.txt'        # 字符集文件
        CHAR_MAX_AMOUNT: 500000   #  中文单字符最大使用次数，达到后停用。只对article类型生效
        CHAR_MAX_SUBSTR: ' '    # 字符停用后的替换字符
        CHAR_MIN_AMOUNT: 1000    # 字符最小使用次数，不足时补充

    CORPUS:
        CORPUS_DIR: 'data/corpus'  # 语料目录
        # 语料类型，不指定时默认为article。
        # 区别为：- article类型遇到换行时直接拼接。
        #        - list类型语料换行时在行尾添加空格
        CORPUS_TYPE: {'sogou_news.txt': 'article', 'address.txt': 'list'}
        # 语料权重，不指定时默认相同
        CORPUS_WEIGHT: {"sogou_news.txt": 0.95, 'address.txt': 0.05}
        INFINITE: True    # 为True时可以循环使用语料

BACKGROUND:
    DIR: 'data/background'  # 背景目录
    SIZE: [32, 400]   # 最终图片大小

EFFECT:
    PYGAME:
        FONTS:
            fonts_dir: 'data/fonts'
            fonts_prob:
                # 中文字体
                SIMFANG.TTF: 0.3  # 仿宋gb2312
                simsun.ttc: 0.1  # 仿宋
                fz-songsan.ttf: 0.1  # 方正宋三

                HanDingJianZhongHei-2.ttf: 0.1   # 汉鼎简中黑
                SIMHEI.TTF: 0.05 # 黑体
                heiti.ttf: 0.05 # 黑体
                MicrosoftYaqiHei-2.ttf: 0.05 # 微软雅旗黑
                fz-heiti.ttf: 0.05  # 方正黑体

                SIMKAI.TTF: 0.1  # 楷体GB2312
                FZSTK.TTF: 0.05  # 方正舒体
                FZYTK.ttf: 0.05  # 方正姚体

                dl-name1.6.otf: 0.01  #
                dl-name2.otf: 0.01  #
                dl-name2.5.otf: 0.01  #

                # 英文字体
                dl-9p.ttf: 0.1
                courbd1.7.ttf: 0.1
                Goodxxt2.ttf: 0.1
                OCR-B_10_BT.ttf: 0.1
                xingshi.ttf: 0.1

            fonts_strong_false: ['FZSTK.TTF', 'FZYTK.ttf']
        FONT_STYLE:
            size: [12, 40, 'u']  # 字体大小, [min, max, mode], mode: u for uniform, g for gaussian
            oblique: 0.05  # 倾斜
            rotation: [0.1, [-5, 5,'u']]  # 旋转
            strong: 0.05  # 加粗
            wide: 0.01  # 加宽
            strength: [0, 0.1, 'u']  # 加粗/加宽的幅度
            underline: [0.01, [0, 2, 'u']]  # 下划线

    OPENCV:
        BOX: 0.05    # 为文字加外边框
        PERSPECTIVE: 0.1  # 透视变换
        PERSPECTIVE_X: [-15, 15, 'g']   # X轴转动角度
        PERSPECTIVE_Y: [-15, 15, 'g']   # Y轴转动角度
        PERSPECTIVE_Z: [-3, 3, 'g']   # Z轴转动角度
        BLUR: 0.1   # 高斯模糊
        BLUR_KSIZE: [1,3,5]
        BLUR_SIGMA: [0, 0.5, 1.5]
        FILTER: [0.01, [0.4, 0.6]]   # filter_prob, emboss_prob, sharp_prob

    MERGE:
        RGB: True   # 是否三通道
        alpha: [0.5, 1.5, 'g']  # 随机调节背景图片的亮度和对比度(a*f(x)+b),调节因子a
        beta: [-100, 100, 'g']   # 随机调节背景图片的亮度和对比度(a*f(x)+b),调节因子b
        font_alpha: [0.2, 1, 'u']  # 文字不透明度
        max_height_diff: 8   # resize时文字图像与背景图最大高度差, 最小值为2
        reverse: 0  # 反转最终图像的颜色
        NOISE: 0.8   # 随机噪点
        NOISE_TYPE: {'gauss':0.1, 'uniform':0.2, 'saltpepper':0.3, 'poisson':0.1}


